# Generated by Django 4.2.1 on 2023-06-09 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombreJunto', models.CharField(max_length=100, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Calles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(default='', max_length=100)),
                ('direccionCorta', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(default='path/to/default/image.jpg', upload_to='categorias/')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('tipo_papas', models.CharField(default='Sin Papas', max_length=100)),
                ('ensalada', models.CharField(default='Sin Ensalada', max_length=100)),
                ('cremas', models.CharField(max_length=100, null=True)),
                ('opcionales', models.TextField(null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('adicionales', models.ManyToManyField(to='eccomerceApp.adicional')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eccomerceApp.carrito')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eccomerceApp.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='PruebaDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('tipo_papas', models.CharField(default='Sin Papas', max_length=100)),
                ('ensalada', models.CharField(default='Sin Ensalada', max_length=100)),
                ('cremas', models.CharField(max_length=100, null=True)),
                ('opcionales', models.TextField(null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('adicionales', models.ManyToManyField(to='eccomerceApp.adicional')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eccomerceApp.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eccomerceApp.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('usuario_id', models.CharField(max_length=100)),
                ('nombreDeCalle', models.CharField(max_length=100, null=True)),
                ('numeroContacto', models.PositiveIntegerField(null=True)),
                ('metodoDePago', models.CharField(default='Efectivo', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vueltoDe', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('items', models.ManyToManyField(to='eccomerceApp.itemscarrito')),
            ],
        ),
        migrations.AddField(
            model_name='itemscarrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eccomerceApp.producto'),
        ),
    ]
