# Generated by Django 4.2.1 on 2023-06-10 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eccomerceApp', '0002_categoriadebebidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemscarrito',
            name='categoria_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eccomerceApp.categoria'),
        ),
    ]
